name: Fork Client

on: [push]

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build.
        env:
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_HASH: ${{ secrets.APP_HASH }}
          HOCKEY_APP_HASH: ${{ secrets.HOCKEY_APP_HASH }}
          USER_ID_OWNER: ${{ secrets.USER_ID_OWNER }}
        run: |
          sudo apt-get install openjdk-8-jdk
          ./gradlew assembleAfatDebug
          grep BUILD_VERSION_STRING TMessagesProj/src/main/java/org/telegram/messenger/BuildVars.java | cut -d'"' -f 2 > ver.txt
          mkdir artifact
          mv TMessagesProj/build/outputs/apk/afat/debug/TMessagesProj-afat-debug.apk artifact/ForkClient_$(cat ver.txt).apk
      - uses: actions/upload-artifact@master
        name: Upload artifact.
        with:
          name: ForkClient
          path: artifact/
